//
// execute.c - part of the Virtual AmigaDOS Machine (VADM)
//             contains the implemented routines of the DOS library
//
// Copyright(C) 2019, 2020 Constantin Wiemer
// 


#include <string.h>
#include <unistd.h>

#include "../execute.h"
#include "../vadm.h"


void dos_put_str()
{
    // use local variable as argument so we can specify the register
    // Although the translated code only uses 32-bit addresses, GCC forces us to specify the full
    // 64-bit registers here. However, this is not a problem because every instruction in 64-bit
    // mode that uses a 32-bit register clears ("zero-extends") the upper 32 bits of the register
    // (see https://stackoverflow.com/questions/11177137/why-do-x86-64-instructions-on-32-bit-registers-zero-the-upper-part-of-the-full-6).
    register const char *str asm("r9");     // D1 => R9D
    write(1, str, strlen(str));
    // set return value
    asm("xorl %r8d, %r8d");                 // D0 => R8D
}


// lines below have been generated with the following command:
// grep libcall /opt/m68k-amigaos//m68k-amigaos/ndk/include/pragmas/dos_pragmas.h | perl -nale 'print "    {0x$F[4], \"$F[3]\", NULL},"'
FuncInfo g_func_info_tbl[] = {
    {0x1e, "Open", NULL},
    {0x24, "Close", NULL},
    {0x2a, "Read", NULL},
    {0x30, "Write", NULL},
    {0x36, "Input", NULL},
    {0x3c, "Output", NULL},
    {0x42, "Seek", NULL},
    {0x48, "DeleteFile", NULL},
    {0x4e, "Rename", NULL},
    {0x54, "Lock", NULL},
    {0x5a, "UnLock", NULL},
    {0x60, "DupLock", NULL},
    {0x66, "Examine", NULL},
    {0x6c, "ExNext", NULL},
    {0x72, "Info", NULL},
    {0x78, "CreateDir", NULL},
    {0x7e, "CurrentDir", NULL},
    {0x84, "IoErr", NULL},
    {0x8a, "CreateProc", NULL},
    {0x90, "Exit", NULL},
    {0x96, "LoadSeg", NULL},
    {0x9c, "UnLoadSeg", NULL},
    {0xae, "DeviceProc", NULL},
    {0xb4, "SetComment", NULL},
    {0xba, "SetProtection", NULL},
    {0xc0, "DateStamp", NULL},
    {0xc6, "Delay", NULL},
    {0xcc, "WaitForChar", NULL},
    {0xd2, "ParentDir", NULL},
    {0xd8, "IsInteractive", NULL},
    {0xde, "Execute", NULL},
    {0xe4, "AllocDosObject", NULL},
    {0xe4, "AllocDosObjectTagList", NULL},
    {0xea, "FreeDosObject", NULL},
    {0xf0, "DoPkt", NULL},
    {0xf0, "DoPkt0", NULL},
    {0xf0, "DoPkt1", NULL},
    {0xf0, "DoPkt2", NULL},
    {0xf0, "DoPkt3", NULL},
    {0xf0, "DoPkt4", NULL},
    {0xf6, "SendPkt", NULL},
    {0xfc, "WaitPkt", NULL},
    {0x102, "ReplyPkt", NULL},
    {0x108, "AbortPkt", NULL},
    {0x10e, "LockRecord", NULL},
    {0x114, "LockRecords", NULL},
    {0x11a, "UnLockRecord", NULL},
    {0x120, "UnLockRecords", NULL},
    {0x126, "SelectInput", NULL},
    {0x12c, "SelectOutput", NULL},
    {0x132, "FGetC", NULL},
    {0x138, "FPutC", NULL},
    {0x13e, "UnGetC", NULL},
    {0x144, "FRead", NULL},
    {0x14a, "FWrite", NULL},
    {0x150, "FGets", NULL},
    {0x156, "FPuts", NULL},
    {0x15c, "VFWritef", NULL},
    {0x162, "VFPrintf", NULL},
    {0x168, "Flush", NULL},
    {0x16e, "SetVBuf", NULL},
    {0x174, "DupLockFromFH", NULL},
    {0x17a, "OpenFromLock", NULL},
    {0x180, "ParentOfFH", NULL},
    {0x186, "ExamineFH", NULL},
    {0x18c, "SetFileDate", NULL},
    {0x192, "NameFromLock", NULL},
    {0x198, "NameFromFH", NULL},
    {0x19e, "SplitName", NULL},
    {0x1a4, "SameLock", NULL},
    {0x1aa, "SetMode", NULL},
    {0x1b0, "ExAll", NULL},
    {0x1b6, "ReadLink", NULL},
    {0x1bc, "MakeLink", NULL},
    {0x1c2, "ChangeMode", NULL},
    {0x1c8, "SetFileSize", NULL},
    {0x1ce, "SetIoErr", NULL},
    {0x1d4, "Fault", NULL},
    {0x1da, "PrintFault", NULL},
    {0x1e0, "ErrorReport", NULL},
    {0x1ec, "Cli", NULL},
    {0x1f2, "CreateNewProc", NULL},
    {0x1f2, "CreateNewProcTagList", NULL},
    {0x1f8, "RunCommand", NULL},
    {0x1fe, "GetConsoleTask", NULL},
    {0x204, "SetConsoleTask", NULL},
    {0x20a, "GetFileSysTask", NULL},
    {0x210, "SetFileSysTask", NULL},
    {0x216, "GetArgStr", NULL},
    {0x21c, "SetArgStr", NULL},
    {0x222, "FindCliProc", NULL},
    {0x228, "MaxCli", NULL},
    {0x22e, "SetCurrentDirName", NULL},
    {0x234, "GetCurrentDirName", NULL},
    {0x23a, "SetProgramName", NULL},
    {0x240, "GetProgramName", NULL},
    {0x246, "SetPrompt", NULL},
    {0x24c, "GetPrompt", NULL},
    {0x252, "SetProgramDir", NULL},
    {0x258, "GetProgramDir", NULL},
    {0x25e, "SystemTagList", NULL},
    {0x25e, "System", NULL},
    {0x264, "AssignLock", NULL},
    {0x26a, "AssignLate", NULL},
    {0x270, "AssignPath", NULL},
    {0x276, "AssignAdd", NULL},
    {0x27c, "RemAssignList", NULL},
    {0x282, "GetDeviceProc", NULL},
    {0x288, "FreeDeviceProc", NULL},
    {0x28e, "LockDosList", NULL},
    {0x294, "UnLockDosList", NULL},
    {0x29a, "AttemptLockDosList", NULL},
    {0x2a0, "RemDosEntry", NULL},
    {0x2a6, "AddDosEntry", NULL},
    {0x2ac, "FindDosEntry", NULL},
    {0x2b2, "NextDosEntry", NULL},
    {0x2b8, "MakeDosEntry", NULL},
    {0x2be, "FreeDosEntry", NULL},
    {0x2c4, "IsFileSystem", NULL},
    {0x2ca, "Format", NULL},
    {0x2d0, "Relabel", NULL},
    {0x2d6, "Inhibit", NULL},
    {0x2dc, "AddBuffers", NULL},
    {0x2e2, "CompareDates", NULL},
    {0x2e8, "DateToStr", NULL},
    {0x2ee, "StrToDate", NULL},
    {0x2f4, "InternalLoadSeg", NULL},
    {0x2fa, "InternalUnLoadSeg", NULL},
    {0x300, "NewLoadSeg", NULL},
    {0x300, "NewLoadSegTagList", NULL},
    {0x306, "AddSegment", NULL},
    {0x30c, "FindSegment", NULL},
    {0x312, "RemSegment", NULL},
    {0x318, "CheckSignal", NULL},
    {0x31e, "ReadArgs", NULL},
    {0x324, "FindArg", NULL},
    {0x32a, "ReadItem", NULL},
    {0x330, "StrToLong", NULL},
    {0x336, "MatchFirst", NULL},
    {0x33c, "MatchNext", NULL},
    {0x342, "MatchEnd", NULL},
    {0x348, "ParsePattern", NULL},
    {0x34e, "MatchPattern", NULL},
    {0x35a, "FreeArgs", NULL},
    {0x366, "FilePart", NULL},
    {0x36c, "PathPart", NULL},
    {0x372, "AddPart", NULL},
    {0x378, "StartNotify", NULL},
    {0x37e, "EndNotify", NULL},
    {0x384, "SetVar", NULL},
    {0x38a, "GetVar", NULL},
    {0x390, "DeleteVar", NULL},
    {0x396, "FindVar", NULL},
    {0x3a2, "CliInitNewcli", NULL},
    {0x3a8, "CliInitRun", NULL},
    {0x3ae, "WriteChars", NULL},
    {0x3b4, "PutStr", dos_put_str},
    {0x3ba, "VPrintf", NULL},
    {0x3c6, "ParsePatternNoCase", NULL},
    {0x3cc, "MatchPatternNoCase", NULL},
    {0x3d8, "SameDevice", NULL},
    {0x3de, "ExAllEnd", NULL},
    {0x3e4, "SetOwner", NULL},
    {0, NULL, NULL}
};
